### ISSUE TITLE
Are we ever going to work on this again?

### ISSUE THREAD

**Issue by m-sterling** [bfox1/SAO#16]
I mean, seriously. This mod had so much potential, and so much work put into it. I know it's been 2+ years since we've gotten together, but seriously. C'mon. Now with Ordinal Scale coming out, everyone will be hyped for SAO again, which gives us more of a reason to revitalise this project. Eh.

**Comment by AoiShadow** [comment]
Perhaps, I mean, I kinda just dropped out of the rader due to school and stuff sadly at that time, though I'm quite free due to being a senior now.

**Comment by Moonless-sky** [comment]
I wouldn't be opposed to working on it again

**Comment by BloodRain** [comment]
Possibly, the reason why all of us kinda drifted away from the mod was we were too busy to work on it. But there is a chance me and bfox will return to it as we mentioned it before between us.

**Comment by ghost** [comment]
I've not been a part of this project for oh a good few years or so. I'm glad to return but I am still as busy as ever. All I wish to do is push out my own projects before I re/join another.

I feel like we should maybe lower our standards as well because recreating ALL of SAO is a bit of a gaint task to handle. We should first focus on smaller things that we can release.

**Comment by bfox1** [comment]
Since my future intention was for it to be a full blown standalone of Sao in minecraft, starting from floor 1 spawn all the way to the end of floor 100. Meaning, we start in the beginning town(forgive me I forgot the name:0) give the player an open world experience, be able to do things outside of an actual quest/ adventure that progresses further to the Floor Boss. 

Before that can be done, A library/API should be designed to handle functionality found on all floors. Ie, Hud, currency, shop api, dungeon library, etc. so that we can create more specific dungeons or shops if we need to.

**Comment by m-sterling** [comment]
@bfox1 The beginning town is, maybe too creatively named, the Town of Beginnings. ¯\\\_(ツ)_/¯

I've been working on a mod that we might be able to borrow from. Things like armour, weapons, skills, etc. I'll work on converting it to more of an API so that we can use it as a library, saving us a decent amount of time. :)

**Comment by bfox1** [comment]
lol ok. Yeah "the town of beginning" granted, I'm at work and I woke up at 6 in the morning with only4 hours of sleep hahaha. I can't think.

But yeah that would help tremendously. Once the API is structured, we begin coding it, once the barebones are done, then it's implementing that api to full use in floor one, during the time of devs creating API, builders build town of beginning and so on.

**Comment by AoiShadow** [comment]
Since Mojang expanded the capabilities of MC, I'm quite sure we'll be able to get the coding back to date, possibly even adding more stuff than before.

**Comment by bfox1** [comment]
Agreed. Capabilities is probably the most ingenious thing they have done so far lol. 

Although, drads world gen code has been messed up badly as 1.10 update seriously modifies many things drads code relies on. So I suppose we would have to figure out how to properly update it

**Comment by bfox1** [comment]
Also, since I have more free time now, I am able to manage the project closer and promote updates. 1.10 seems more laggy to me then 1.8.9 but idk. It's up to you guys to decide which version is more beneficial

**Comment by bfox1** [comment]
@kkirigaya https://github.com/bfox1/McSao Please check out that. i am attempting to fix all errors in the 1.10 port over. hopefully things go smoothly

**Comment by m-sterling** [comment]
@bfox1 Well, like @AoiShadow said, Minecraft has a lot more capabilities now, so it should be easier to implement some of the things we were thinking about adding. ¯\_(ツ)_/¯ We’ll have to see, I guess.

**Comment by bfox1** [comment]
Me and dead were talking. And we discovered some interesting things about capabilities. It's useful for sure but it also means we must be smart in checking for capabilities. Since capabilities stores everything literally... Including "forge energy" which we won't be using pretty much, it can lag up the server if we are not smart and careful about our code.

**Comment by Dradgit** [comment]
bfox and I have been working on this for a few days. I dunno what you guys have discussed outside of this but the dev branch has several changes that update it to 1.10.2 now and get a few things functional again, such as world gen. Also started working on the dungeon gen, which has the basics working now!

**Comment by m-sterling** [comment]
@igraham Awesome!

Since most of you still seem interested, I say we should switch our conversation from this issue, haha. Say, Discord or IRC? I'm still on EsperNet, maybe we can make a new channel. `#mcsao-new`, maybe? Discord is also an option, since Skype is a bit too bulky IMO. :)

**Comment by Dradgit** [comment]
Already done on discord. Instant Invite Code: mdQkYY4
